CREATE TABLE IF NOT EXISTS dms (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  battlefield JSONB DEFAULT '[]',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS characters (
  id UUID PRIMARY KEY,
  dm_id INTEGER NOT NULL REFERENCES dms(id) ON DELETE CASCADE,
  name VARCHAR(100) NOT NULL,
  class VARCHAR(50),
  species VARCHAR(50),
  level INTEGER DEFAULT 1,
  background VARCHAR(100),
  hp INTEGER DEFAULT 10,
  ac INTEGER DEFAULT 10,
  str INTEGER DEFAULT 10,
  dex INTEGER DEFAULT 10,
  con INTEGER DEFAULT 10,
  int INTEGER DEFAULT 10,
  wis INTEGER DEFAULT 10,
  cha INTEGER DEFAULT 10,
  skills JSONB DEFAULT '[]',
  features JSONB DEFAULT '[]',
  currency JSONB DEFAULT '{"CP":0,"SP":0,"EP":0,"GP":0,"PP":0}',
  equipment JSONB DEFAULT '[]',
  spells JSONB DEFAULT '[]',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sessions (
  id SERIAL PRIMARY KEY,
  dm_id INTEGER UNIQUE NOT NULL REFERENCES dms(id) ON DELETE CASCADE,
  pin VARCHAR(20) NOT NULL,
  characters JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_characters_dm_id ON characters(dm_id);
CREATE INDEX IF NOT EXISTS idx_sessions_dm_id ON sessions(dm_id);
